@hostname = LED-Dev
@port = 1234
@token = token SUPERSECRETCODE

###
POST http://{{hostname}}:{{port}}/api/v2/notification/centertoside HTTP/1.1
Content-Type: application/json
Authorization: Basic {{token}}

{
  "notification": {
    "duration": 10,
    "colors": [
      {"r": 255, "g": 20, "b": 0, "a": 1},
      {"r": 0, "g": 255, "b": 0, "a": 1}
      //{"r": 0, "g": 0, "b": 255, "a": 1},
      //{"r": 255, "g": 20, "b": 0, "a": 1},
      //{"r": 0, "g": 255, "b": 0, "a": 1},
      //{"r": 0, "g": 0, "b": 255, "a": 1}
    ]
  }
}

###
POST http://{{hostname}}:{{port}}/api/v2/notification/blink HTTP/1.1
Content-Type: application/json
Authorization: Basic {{token}}

{
  "notification": {
    "duration": 60,
    "colors": [
      {"r": 255, "g": 20, "b": 0, "a": 1},
      {"r": 0, "g": 255, "b": 0, "a": 1}
      //{"r": 0, "g": 0, "b": 255, "a": 1},
      //{"r": 255, "g": 20, "b": 0, "a": 1},
      //{"r": 0, "g": 255, "b": 0, "a": 1},
      //{"r": 0, "g": 0, "b": 255, "a": 1}
    ]
  }
}

###
POST http://{{hostname}}:{{port}}/api/v2/notification/rippletocenter HTTP/1.1
Content-Type: application/json
Authorization: Basic {{token}}

{
  "notification": {
    "duration": 60,
    "color": {"r": 255, "g": 20, "b": 0, "a": 1},
    "keepAnimationRunning": true
  }
}