@hostname = LED-Dev
@port = 1234
@token = token SUPERSECRETCODE


###  START                                                  
POST http://{{hostname}}:{{port}}/api/v2/start HTTP/1.1
Content-Type: application/json
Authorization: Basic {{token}}

{
  "update_per_second": 60
}

###                                                  
POST http://{{hostname}}:{{port}}/api/v2/persistent/settings/mode HTTP/1.1
Content-Type: application/json
Authorization: Basic {{token}}

{
  "options": {
    "mode": 1,
    "startLED": 120
  }
}


### STOP
GET http://{{hostname}}:{{port}}/api/v2/stop HTTP/1.1
Authorization: Basic {{token}}

### STATUS
GET http://{{hostname}}:{{port}}/api/v2/status HTTP/1.1
Authorization: Basic {{token}}